site_name: {{cookiecutter.project_name}} Docs
site_author: {{cookiecutter.full_name}}
use_directory_urls: true
# google_analytics: ['UA-ID', '{{cookiecutter.domain}}']


copyright: Copyright &copy; 2021 – X Studios™, Inc.

# Configuration
theme:
    name: "material"
    palette:
        scheme: default
    icon:
        repo: fontawesome/brands/git-alt
    favicon: images/favicon.png
    logo: img/x_x_white.svg
    font:
        text: Raleway
        code: Roboto Mono
    features:
        - instant
        - tabs

# Extensions
markdown_extensions:
    - abbr
    - attr_list
    - tables
    - admonition
    - sane_lists
    - smarty
    - toc:
          toc_depth: 2
          permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details
    - pymdownx.highlight:
          use_pygments: true
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.tilde
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
    - search
    - awesome-pages
    - minify:
          minify_html: true
          minify_js: true

# Customization
extra_css:
    - css/extra.css
    # - https://domain.com/styles.css

extra_javascript:
    # - https://domain.com/javascript.js

# Page tree
nav:
  - Getting Started:
    - index.md
    - help.md


extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/xstudios
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/xstudiosinc
        - icon: fontawesome/brands/instagram
          link: https://instagram.com/xstudios
