version: '3'

services:
  mkdocs:
    build:
      context: .
      dockerfile: ./compose/mkdocs/Dockerfile
    image: {{cookiecutter.project_slug}}_mkdocs
    container_name: {{cookiecutter.project_slug}}_mkdocs
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    command: /entrypoint
    restart: always
