site_name: {{cookiecutter.project_name}} Docs
site_author: {{cookiecutter.full_name}}
use_directory_urls: true
# google_analytics: ['UA-ID', '{{cookiecutter.domain}}']


copyright: Copyright &copy; 20XX – X Studios™, Inc.

# Configuration
theme:
    name: "material"
    palette:
        scheme: default
        primary: custom
        accent: custom
    icon:
        repo: fontawesome/brands/git-alt
    favicon: images/favicon.png
    logo: img/x_x_white.svg
    font:
        text: Raleway
        code: Roboto Mono
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.tabs.sticky
        - navigation.top
        # - navigation.footer
        # - navigation.tracking
        # - toc.integrate
        - content.code.copy

# Extensions
markdown_extensions:
    - abbr
    - attr_list
    - tables
    - admonition
    - sane_lists
    - smarty
    - meta
    - toc:
          toc_depth: 2
          permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.details
    - pymdownx.highlight:
          use_pygments: true
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tilde
    # - fontawesome_markdown

# Plugins
plugins:
    - search
    - awesome-pages
    - minify:
          minify_html: true
          minify_js: true

# Customization
extra_css:
    - css/extra.css
    # - https://use.typekit.net/pkv5qkr.css
    # - https://domain.com/styles.css
    # - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css

# extra_javascript:
    # - https://domain.com/javascript.js

# Page tree
nav:
  - Getting Started:
    - index.md
    - help.md


extra:
    generator: false
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/xstudios
        - icon: fontawesome/brands/facebook
          link: https://facebook.com/xstudiosinc
        - icon: fontawesome/brands/instagram
          link: https://instagram.com/xstudios
