[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material[imaging]>=9.6.11",
    "mkdocs-minify-plugin>=0.8.0",
]
